### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by jprocks101** [Norikiru/bloxflip-autocrash#21]
Error: ENOENT: no such file or directory, open 'C:\Users\\Downloads\bloxflip-autocrash-main\bloxflip-autocrash-main\bloxflip-autocrash\config.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at file:///C:/Users//Downloads/bloxflip-autocrash-main/bloxflip-autocrash-main/bloxflip-autocrash/src/utils/config.ts:40:39
    at fetchCfg (file:///C:/Users//Downloads/bloxflip-autocrash-main/bloxflip-autocrash-main/bloxflip-autocrash/src/utils/config.ts:51:10)
    at file:///C:/Users//Downloads/bloxflip-autocrash-main/bloxflip-autocrash-main/bloxflip-autocrash/src/index.ts:16:11
    at file:///C:/Users//Downloads/bloxflip-autocrash-main/bloxflip-autocrash-main/bloxflip-autocrash/src/index.ts:40:2
    at ModuleJob.run (node:internal/modules/esm/module_job:197:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async loadESM (node:internal/process/esm_loader:88:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\\\Downloads\\bloxflip-autocrash-main\\bloxflip-autocrash-main\\bloxflip-autocrash\\config.json'}

**Comment by nikosszzz** [comment]
Error is self-explanatory - You haven’t created the `config.json` file required that has your Bloxflip auth token alongside other settings.

**Comment by carince** [comment]
Closed due to inactivity, reopen again when you still need assistance.
