### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AmITato** [Norikiru/bloxflip-autocrash#28]
Upon trying to install this I get the following error:
C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:1083
    const err = new SyntaxError(message)
                ^
SyntaxError: JSON5: invalid character '\"' at 6:9
    at syntaxError (C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:1083:17)
    at invalidChar (C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:1028:12)
    at Object.afterPropertyValue (C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:654:15)
    at Object.default (C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:146:37)
    at lex (C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:78:42)
    at Object.parse (C:\Users\Piano\Downloads\bloxflip-autocrash-dev\bloxflip-autocrash-dev\node_modules\json5\lib\parse.js:25:17)
    at file:///C:/Users/Piano/Downloads/bloxflip-autocrash-dev/bloxflip-autocrash-dev/src/utils/config.ts:40:33
    at fetchCfg (file:///C:/Users/Piano/Downloads/bloxflip-autocrash-dev/bloxflip-autocrash-dev/src/utils/config.ts:51:10)
    at file:///C:/Users/Piano/Downloads/bloxflip-autocrash-dev/bloxflip-autocrash-dev/src/index.ts:16:11
    at file:///C:/Users/Piano/Downloads/bloxflip-autocrash-dev/bloxflip-autocrash-dev/src/index.ts:40:2 {
  lineNumber: 6,
  columnNumber: 9
}

**Comment by AmITato** [comment]
Even with the normal branch, same error

**Comment by carince** [comment]
This probably because your JSON file is invalid, redo your config and see if the problem persists.

You can also reinstall all the modules by doing the following:
1. Delete the `node_modules` folder.
2. Run PowerShell inside of the `bloxflip-autocrash` folder.
3. Run the command: `npm i`

**Comment by KaidenTheCEO** [comment]
I'm also getting an error. npm ERR! Missing script: "start"
