### ISSUE TITLE
Rain error and crashing the browser

### ISSUE THREAD

**Issue by llllxzllll** [Norikiru/bloxflip-autocrash#48]
`C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228
throw new Error('Evaluation failed: ' + (0, util_js_1.getExceptionMessage)(exceptionDetails));
^

Error: Evaluation failed: TypeError: Cannot read properties of undefined (reading 'rain')
at pptr://puppeteer_evaluation_script:1:123
at ExecutionContext._ExecutionContext_evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:228:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ExecutionContext.evaluate (C:\Users\Administrator\Downloads\bloxflip-autocrash-main\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
at async U (file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:5:613)
at async file:///C:/Users/Administrator/Downloads/bloxflip-autocrash-main/dist/index.js:28:336

Node.js v20.9.0
`

**Comment by carince** [comment]
I still need to recreate the bug, for the meantime, please update your current bloxflip-autocrash to `2.2.0` since it has updated the URL's necessary for the bot to work. If the problem still continues, I also recommend to disable rain through the config.

**Comment by llllxzllll** [comment]
I already managed to solve my friend, could you tell me a good configuration for "config.json5"?

**Comment by carince** [comment]
> I already managed to solve my friend, could you tell me a good configuration for "config.json5"?

There is no "good" configuration per se, but the default config of 13 tries and auto cashout at 2x should be good enough.
